[package]
name = "datatest-mini"
version = "0.3.0"
edition = "2024"
rust-version = "1.85"
description = "Minimal proc_macro for generating test functions from fixture files"
license = "MIT"
repository = "https://github.com/wado-lang/datatest-mini"

[lib]
proc-macro = true

[dependencies]
regex = "1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
